version: "3.8"
services:
  db:
    image: postgres
    container_name: clinica_local_pgdb
    # restart: always
    ports:
      - "5401:5432"
    environment:
      POSTGRES_USER: clinica
      POSTGRES_PASSWORD: clinica123
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  # uncomment this code in case you don't have an sql administrator
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: clinica_pgadmin4_container
  #   restart: always
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: cristiansotomayor@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: